# Generated by Django 5.1.5 on 2025-01-30 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymfrangos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
