# Generated by Django 5.1.5 on 2025-03-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body_part', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('gif_url', models.URLField()),
                ('target', models.CharField(max_length=100)),
                ('secondaryMuscles', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=300)),
                ('series', models.IntegerField(default=3)),
                ('repetitions', models.IntegerField(default=10)),
                ('difficulty', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='beginner', max_length=12)),
            ],
        ),
    ]
