# Generated by Django 5.1.5 on 2025-02-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('body_part', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('gif_url', models.URLField()),
                ('series', models.IntegerField(default=3)),
                ('repetitions', models.IntegerField(default=10)),
            ],
        ),
    ]
